version: "2"

services:
  revealjs:
    image: uphy/reveal.js:3.7.0
    ports:
      - "8000:8000"
      - "35729:35729"
    volumes:
      - "./data:/reveal.js/data"
      - "./docs:/reveal.js/build"
  # juiceshop:
  #   image: bkimminich/juice-shop
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     # - NODE_ENV=tutorial
  #     - NODE_ENV=ctf
